name: Build and Release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: "gradle"

      - name: Build project
        run: bash ./gradlew assembleDebug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact.zip
          path: app/build/outputs/apk/debug/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact.zip

      - name: Set timestamp for release
        run: |
          release_timestamp=$(date +%Y%m%d%H%M%S)
          echo "release_timestamp=${release_timestamp}" >> $GITHUB_ENV
          echo "release_tag_name=release-${release_timestamp}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.release_tag_name }}"
          release_name: "Release ${{ env.release_timestamp }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./*
          file_glob: true
          tag: "${{ env.release_tag_name }}"
